// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ8lMdaRimyIjo0WHTOH57Q2zjsFcyZ7M',
    appId: '1:292105313301:web:426e7db5f58d8bb141c21c',
    messagingSenderId: '292105313301',
    projectId: 'exeed-4e1fb',
    authDomain: 'exeed-4e1fb.firebaseapp.com',
    storageBucket: 'exeed-4e1fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIOU4Pheie2LeEbVtIzO8prEqzrWD5ys',
    appId: '1:292105313301:android:1a899f46c68b116641c21c',
    messagingSenderId: '292105313301',
    projectId: 'exeed-4e1fb',
    storageBucket: 'exeed-4e1fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZbLMdlh-I4KGjNTn7ySCvR2GdYy7n_NI',
    appId: '1:292105313301:ios:7edee5396a67d0be41c21c',
    messagingSenderId: '292105313301',
    projectId: 'exeed-4e1fb',
    storageBucket: 'exeed-4e1fb.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZbLMdlh-I4KGjNTn7ySCvR2GdYy7n_NI',
    appId: '1:292105313301:ios:7edee5396a67d0be41c21c',
    messagingSenderId: '292105313301',
    projectId: 'exeed-4e1fb',
    storageBucket: 'exeed-4e1fb.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ8lMdaRimyIjo0WHTOH57Q2zjsFcyZ7M',
    appId: '1:292105313301:web:490bbd74ba5242fb41c21c',
    messagingSenderId: '292105313301',
    projectId: 'exeed-4e1fb',
    authDomain: 'exeed-4e1fb.firebaseapp.com',
    storageBucket: 'exeed-4e1fb.firebasestorage.app',
  );
}
